name: app_nckh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^1.2.1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

  # UI & Chat
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2  
  pin_code_fields: ^8.0.1

  # Camera & Video
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  flutter_tts: ^3.8.3
  chewie: ^1.7.5
  better_player: ^0.0.84  # stable bản pub.dev, tránh lỗi AndroidManifest

  # Cupertino
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/google.png
    - assets/img/facebook.png
    - assets/img/github.png
    - assets/img/lock.png
    - assets/img/logoMobile.png
    - assets/img/logoVietNam.png
    - assets/img/signSmartLogo.png
    - assets/img/SignSmart_Logo_TrongSuot.png
