{
    "ban_yeu_toi": "Bạn yêu tôi",
    "toi_yeu_ban_ay": "Tôi yêu bạn ấy",
    "ban_ay_yeu_toi": "Bạn ấy yêu tôi",
    "ban_yeu_ban_ay": "Bạn yêu bạn ấy",
    "ban_ay_yeu_ban": "Bạn ấy yêu bạn",
    "anh_hai_anh_ca": "Anh hai, anh cả",
    "chi_hai_chi_ca": "Chị hai, chị cả",
    "qua_bau_ho_lo": "Quả bầu hồ lô",
    "mot_la": "Một là",
    "hai_la": "Hai là",
    "ba_la": "Ba là",
    "bon_la": "Bốn là",
    "nam_la": "Năm là",
    "ong_ba": "Ông bà",
    "em_ho": "Em họ",
    "chau_ho": "Cháu họ",
    "song_sot": "Sống sót",
    "thuong_xuyen": "Thường xuyên",
    "di_dao": "Đi dạo",
    "ve_sai_gon": "Về (Sài Gòn)",
    "phong_toa": "Phong toả",
    "thung_lung": "Thung lũng",
    "dia_hinh": "Địa hình",
    "kim_dong": "Kim đồng",
    "thanh_giong": "Thánh gióng",
    "hoa_giay": "Hoa giấy",
    "hoa_dam_but": "Hoa dâm bụt",
    "ket_luan": "Kết luận",
    "internet": "Internet",
    "di_ve_sinh": "Đi vệ sinh",
    "hoa_mai": "Hoa mai",
    "aw": "ă",
    "aa": "â",
    "b": "b",
    "c": "c",
    "d": "d",
    "dd": "đ",
    "e": "e",
    "g": "g",
    "h": "h",
    "i": "i",
    "k": "k",
    "l": "l",
    "m": "m",
    "n": "n",
    "o": "o",
    "ow": "ơ",
    "p": "p",
    "q": "q",
    "r": "r",
    "s": "s",
    "t": "t",
    "u": "u",
    "v": "v",
    "x": "x",
    "y": "y",
    "z": "z",
    "f": "f",
    "j": "j",
    "dau_huyen": "Dấu huyền",
    "dau_sac": "Dấu sắc",
    "dau_hoi": "Dấu hỏi",
    "dau_nang": "Dấu nặng",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10"
}
